---
  - name: DOCKER CE - install Docker CE SELinux dependancy
    yum:
      name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-selinux-17.03.3.ce-1.el7.noarch.rpm
      state: present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
    register: docker_result
    until: docker_result is success
    retries: 3
    delay: 5

  - name: DOCKER CE - install Docker CE application container engine
    yum:
      name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-17.03.2.ce-1.el7.centos.x86_64.rpm
      state: present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
    register: docker_result
    until: docker_result is success
    retries: 3
    delay: 5

  - name: DOCKER CE - enable and start Docker CE
    systemd:
      name: docker
      state: started

  - name: DOCKER CE - add docker user group
    group:
      name: docker
      state: present
    register: group_result

  - name: DOCKER CE - add vagrant user to docker group
    user:
      name: vagrant
      shell: /bin/bash
      groups: docker
      append: yes
    register: user_group_result

#  - debug:
#      var: group_result
#  - debug:
#      var: user_group_result
#  - debug:
#      var: docker_result